//! Validate `docs/agentmesh-docs.toml` and generate the embedded docs registry.

use std::collections::HashSet;
use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

const EXPECTED_SCHEMA_VERSION: &str = "agentmesh-docs.v0";
const DOCS_PREFIX: &str = "docs/";

#[derive(Debug, serde::Deserialize)]
struct Catalog {
    schema_version: String,
    documents: Vec<CatalogDocument>,
}

#[derive(Debug, serde::Deserialize)]
struct CatalogDocument {
    name: String,
    description: String,
    source: String,
}

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir.join("../..");
    let catalog_path = workspace_root.join("docs/agentmesh-docs.toml");

    println!("cargo:rerun-if-changed={}", catalog_path.display());
    println!(
        "cargo:rustc-env=AGENTMESH_WORKSPACE_ROOT={}",
        workspace_root.display()
    );

    let catalog_text = fs::read_to_string(&catalog_path)
        .unwrap_or_else(|err| panic!("read {}: {err}", catalog_path.display()));
    let catalog: Catalog = toml::from_str(&catalog_text)
        .unwrap_or_else(|err| panic!("parse {}: {err}", catalog_path.display()));

    validate_catalog(&catalog, &workspace_root);

    for document in &catalog.documents {
        println!(
            "cargo:rerun-if-changed={}",
            workspace_root.join(&document.source).display()
        );
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("docs_registry.rs");
    write_registry(&out_path, &catalog).unwrap_or_else(|err| {
        panic!("write {}: {err}", out_path.display());
    });
}

fn validate_catalog(catalog: &Catalog, workspace_root: &Path) {
    if catalog.schema_version != EXPECTED_SCHEMA_VERSION {
        panic!(
            "catalog schema_version must be {EXPECTED_SCHEMA_VERSION:?}, got {:?}",
            catalog.schema_version
        );
    }

    let mut seen_names = HashSet::new();
    for document in &catalog.documents {
        if document.name.trim().is_empty() {
            panic!("catalog document name must not be empty");
        }
        if !seen_names.insert(document.name.clone()) {
            panic!("duplicate catalog document name: {}", document.name);
        }
        if document.description.trim().is_empty() {
            panic!("catalog document {:?} has empty description", document.name);
        }
        validate_source(&document.name, &document.source, workspace_root);
    }
}

fn validate_source(name: &str, source: &str, workspace_root: &Path) {
    if source.trim().is_empty() {
        panic!("catalog document {name:?} has empty source");
    }
    if !source.starts_with(DOCS_PREFIX) {
        panic!("catalog document {name:?} source must start with {DOCS_PREFIX:?}, got {source:?}");
    }
    if !source.ends_with(".md") {
        panic!("catalog document {name:?} source must be Markdown (.md), got {source:?}");
    }
    if source.contains('\\') {
        panic!("catalog document {name:?} source must use forward slashes, got {source:?}");
    }

    let file_name = Path::new(source)
        .file_name()
        .and_then(|value| value.to_str())
        .unwrap_or("");
    if file_name == "AGENTS.md" {
        panic!("catalog document {name:?} must not reference AGENTS.md");
    }
    for prefix in ["pr-draft-", "release-draft-", "repair-"] {
        if file_name.starts_with(prefix) {
            panic!(
                "catalog document {name:?} source {source:?} matches excluded prefix {prefix:?}"
            );
        }
    }

    let absolute = workspace_root.join(source);
    if !absolute.is_file() {
        panic!(
            "catalog document {name:?} source missing: {}",
            absolute.display()
        );
    }
}

fn write_registry(out_path: &Path, catalog: &Catalog) -> std::io::Result<()> {
    let mut file = fs::File::create(out_path)?;
    writeln!(
        file,
        "// @generated by crates/agentmesh-cli/build.rs — do not edit."
    )?;
    writeln!(file, "#[derive(Debug, Clone, Copy)]")?;
    writeln!(
        file,
        "#[allow(dead_code)] pub struct EmbeddedDoc {{ pub name: &'static str, pub description: &'static str, pub source: &'static str, pub content: &'static str }}"
    )?;
    writeln!(file, "pub static EMBEDDED_DOCS: &[EmbeddedDoc] = &[")?;
    for document in &catalog.documents {
        writeln!(
            file,
            "    EmbeddedDoc {{ name: {:?}, description: {:?}, source: {:?}, content: include_str!(concat!(env!(\"AGENTMESH_WORKSPACE_ROOT\"), \"/{}\")), }},",
            document.name, document.description, document.source, document.source
        )?;
    }
    writeln!(file, "];")?;
    Ok(())
}
